#!/usr/bin/env python3
import html
import sys
import threading
import time

import dbus
from dbus.mainloop.glib import DBusGMainLoop, threads_init
from gi.repository import GLib


class SpotifyBlocklet:

    BUS_NAME = 'org.mpris.MediaPlayer2.spotify'
    OBJECT_PATH = '/org/mpris/MediaPlayer2'
    PLAYER_INTERFACE = 'org.mpris.MediaPlayer2.Player'
    PROPERTIES_INTERFACE = 'org.freedesktop.DBus.Properties'

    STATUS_TO_ICON = {
        'Playing': '',
        'Paused': '',
        'Stopped': '',
    }

    BUTTON_TO_MPRIS_METHOD = {
        1: 'PlayPause',   # left button
        4: 'Next',   # wheel up
        5: 'Previous',   # wheel down
    }

    loop = None

    def __init__(self):
        self._handle_input_thread = threading.Thread(
            target=self.handle_input, daemon=True)

    def handle_input(self):
        while True:
            try:
                button = int(input())
            except ValueError:
                continue
            method_name = self.BUTTON_TO_MPRIS_METHOD.get(button)
            if method_name:
                getattr(self.spotify, method_name)(
                    dbus_interface=self.PLAYER_INTERFACE)

    def init_loop(self):
        self.loop = GLib.MainLoop()
        # See: https://dbus.freedesktop.org/doc/dbus-python/
        # dbus.mainloop.html?highlight=thread#dbus.mainloop.glib.threads_init
        threads_init()
        DBusGMainLoop(set_as_default=True)

    def _run(self):
        self.bus = dbus.SessionBus()
        self.spotify = self.bus.get_object(
            bus_name=self.BUS_NAME,
            object_path=self.OBJECT_PATH,
            follow_name_owner_changes=True,
        )
        self.connect_to_dbus_signals()
        self.show_initial_info()
        self.loop.run()

    def run(self, *, init_loop=False, forever=False):
        if init_loop:
            self.init_loop()
        elif self.loop is None:
            raise RuntimeError(
                'Loop is not initialized; call init_loop() first.')
        self._handle_input_thread.start()
        while True:
            try:
                self._run()
            except dbus.exceptions.DBusException:
                time.sleep(1)
            except KeyboardInterrupt:
                break
            finally:
                if not forever:
                    break
        self.loop.quit()

    def connect_to_dbus_signals(self):
        self.spotify.connect_to_signal(
            signal_name='PropertiesChanged',
            handler_function=self.on_properties_changed,
            dbus_interface=self.PROPERTIES_INTERFACE,
        )
        self.bus.get_object(
            bus_name='org.freedesktop.DBus',
            object_path='/org/freedesktop/DBus',
        ).connect_to_signal(
            signal_name='NameOwnerChanged',
            handler_function=self.on_name_owner_changed,
            dbus_interface='org.freedesktop.DBus',
            arg0=self.BUS_NAME,
        )

    def on_properties_changed(self, interface_name, changed_properties, _):
        """Show updated info when playback status or track is changed"""
        self.show_info(
            status=changed_properties['PlaybackStatus'],
            metadata=changed_properties['Metadata'],
        )

    def on_name_owner_changed(self, name, old_owner, new_owner):
        """Clear info when Spotify is closed"""
        if old_owner and not new_owner:
            print(' ')
            sys.stdout.flush()

    def get_property(self, property_name):
        return self.spotify.Get(
            self.PLAYER_INTERFACE, property_name,
            dbus_interface=self.PROPERTIES_INTERFACE,
        )

    def show_initial_info(self):
        self.show_info(
            status=self.get_property('PlaybackStatus'),
            metadata=self.get_property('Metadata'),
        )

    def show_info(self, status, metadata):
        status_icon = self.STATUS_TO_ICON.get(status, '?')
        artist = ', '.join(metadata['xesam:artist'])
        title = metadata['xesam:title']
        info = '{status_icon} {artist} — {title}'.format(
            status_icon=status_icon,
            artist=artist,
            title=title,
        )
        print(html.escape(info))
        sys.stdout.flush()


if __name__ == '__main__':
    SpotifyBlocklet().run(init_loop=True, forever=True)
